---
- name: azurevmcreatenet
  hosts: all

  tasks:

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: Test
      name: Test-vnet
      address_prefixes: "10.10.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: Test
      name: subnet001
      address_prefix: "10.10.0.0/24"
      virtual_network: Test-vnet

  - name: Create public ip
    azure_rm_publicipaddress:
      resource_group: Test
      allocation_method: Dynamic
      name: test01-ip